// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AcademicsAssignment struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	ClassID     uuid.UUID
	SubjectID   uuid.UUID
	TeacherID   uuid.UUID
	Title       sql.NullString
	Description sql.NullString
	DueDate     sql.NullTime
	MaxMarks    sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type AcademicsClassPeriod struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	StartTime   time.Time
	EndTime     time.Time
	IsBreak     sql.NullBool
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type AcademicsLessonPlan struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	ClassID        uuid.UUID
	SubjectID      uuid.UUID
	TeacherID      uuid.UUID
	Topic          sql.NullString
	PlannedDate    sql.NullTime
	CompletionDate sql.NullTime
	Status         sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type AcademicsStudentSubject struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.NullUUID
	StudentID         uuid.NullUUID
	SubjectID         uuid.NullUUID
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
}

type AcademicsStudentSubmission struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	AssignmentID  uuid.UUID
	StudentID     uuid.UUID
	SubmissionUrl sql.NullString
	SubmittedAt   sql.NullTime
	MarksObtained sql.NullString
	Feedback      sql.NullString
	Status        sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type AcademicsSubject struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	Code        sql.NullString
	Type        sql.NullString
	Credits     sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type AcademicsSubstitution struct {
	ID                  uuid.UUID
	InstituteID         uuid.UUID
	TimetableEntryID    uuid.NullUUID
	OriginalTeacherID   uuid.NullUUID
	SubstituteTeacherID uuid.NullUUID
	Date                time.Time
	Reason              sql.NullString
	IsActive            sql.NullBool
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
}

type AcademicsTimetableEntry struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	ClassID           uuid.NullUUID
	PeriodID          uuid.NullUUID
	SubjectID         uuid.NullUUID
	TeacherID         uuid.NullUUID
	DayOfWeek         sql.NullString
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type AdmissionsEnquiry struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	StudentName  sql.NullString
	GuardianName sql.NullString
	Phone        sql.NullString
	Email        sql.NullString
	Status       sql.NullString
	EnquiryDate  sql.NullTime
	FollowUpDate sql.NullTime
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type AlumniDonation struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	AlumniID       uuid.NullUUID
	Amount         sql.NullString
	DonationDate   sql.NullTime
	Purpose        sql.NullString
	TransactionRef sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type AlumniProfile struct {
	ID                  uuid.UUID
	InstituteID         uuid.UUID
	StudentID           uuid.NullUUID
	GraduationYear      sql.NullInt32
	CurrentOrganization sql.NullString
	Designation         sql.NullString
	LinkedinUrl         sql.NullString
	IsActiveMember      sql.NullBool
	IsActive            sql.NullBool
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
}

type AuthUser struct {
	ID              uuid.UUID
	Username        sql.NullString
	Email           sql.NullString
	PhoneNumber     sql.NullString
	UsernameHash    string
	EmailHash       string
	PhoneNumberHash sql.NullString
	PasswordHash    string
	RoleType        sql.NullString
	LinkedEntityID  uuid.UUID
	InstituteID     uuid.NullUUID
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type CafeteriaDailyMenu struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Date        sql.NullTime
	MealType    sql.NullString
	Items       sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type CafeteriaMealPlan struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	Name         sql.NullString
	CostPerMonth sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type CafeteriaStudentSubscription struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	StudentID   uuid.NullUUID
	PlanID      uuid.NullUUID
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type CommsEmailLog struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	RecipientEmail sql.NullString
	Subject        sql.NullString
	Status         sql.NullString
	SentAt         sql.NullTime
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type CommsNotification struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	UserID      uuid.NullUUID
	Title       sql.NullString
	Message     sql.NullString
	IsRead      sql.NullBool
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CommsSmsLog struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	RecipientPhone sql.NullString
	MessageBody    sql.NullString
	Status         sql.NullString
	ProviderID     sql.NullString
	SentAt         sql.NullTime
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type CoreAcademicSession struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CoreAddress struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	OwnerType    sql.NullString
	AddressType  sql.NullString
	AddressLine1 string
	AddressLine2 sql.NullString
	CountryID    uuid.NullUUID
	StateID      uuid.NullUUID
	DistrictID   uuid.NullUUID
	PostalCode   sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type CoreApproval struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Module      sql.NullString
	ReferenceID uuid.UUID
	ApproverID  uuid.NullUUID
	Status      sql.NullString
	Remarks     sql.NullString
	ApprovedAt  sql.NullTime
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type CoreCalendarEvent struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	Title          string
	Description    sql.NullString
	StartDate      time.Time
	EndDate        time.Time
	EventType      sql.NullString
	IsHoliday      sql.NullBool
	TargetAudience sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type CoreClass struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	Name              string
	Section           string
	ClassTeacherID    uuid.NullUUID
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type CoreDepartment struct {
	ID          uuid.UUID
	InstituteID uuid.NullUUID
	Name        string
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CoreEmployee struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	EmployeeCode       string
	FirstName          sql.NullString
	LastName           sql.NullString
	DepartmentID       uuid.NullUUID
	Gender             sql.NullString
	MaritalStatus      sql.NullString
	DateOfJoining      sql.NullTime
	Nationality        sql.NullString
	PreferredLanguage  sql.NullString
	SocialMediaHandles pqtype.NullRawMessage
	LanguageSkills     pqtype.NullRawMessage
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type CoreGuardian struct {
	ID           uuid.UUID
	FirstName    sql.NullString
	LastName     sql.NullString
	Email        sql.NullString
	Phone        sql.NullString
	EmailHash    sql.NullString
	PhoneHash    sql.NullString
	Profession   sql.NullString
	AnnualIncome sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type CoreInstitute struct {
	ID                   uuid.UUID
	Name                 string
	Code                 string
	CurrencyCode         sql.NullString
	LogoUrl              sql.NullString
	Website              sql.NullString
	Timezone             sql.NullString
	FiscalYearStartMonth sql.NullInt32
	IsActive             sql.NullBool
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	DeletedAt            sql.NullTime
	CreatedBy            uuid.NullUUID
	UpdatedBy            uuid.NullUUID
}

type CoreStudent struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	AdmissionNo        string
	FirstName          sql.NullString
	LastName           sql.NullString
	Dob                sql.NullTime
	Gender             sql.NullString
	BloodGroup         sql.NullString
	SocialCategory     sql.NullString
	CurrentClassID     uuid.NullUUID
	Nationality        sql.NullString
	PreferredLanguage  sql.NullString
	SocialMediaHandles pqtype.NullRawMessage
	LanguageSkills     pqtype.NullRawMessage
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type CoreStudentGuardianMap struct {
	StudentID        uuid.UUID
	GuardianID       uuid.UUID
	Relationship     sql.NullString
	IsPrimaryContact sql.NullBool
	IsActive         sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	DeletedAt        sql.NullTime
}

type CoreStudentSessionHistory struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	StudentID         uuid.UUID
	AcademicSessionID uuid.UUID
	ClassID           uuid.UUID
	RollNumber        sql.NullString
	Status            sql.NullString
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type DisciplineAction struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	IncidentID  uuid.NullUUID
	ActionType  sql.NullString
	StartDate   sql.NullTime
	EndDate     sql.NullTime
	Remarks     sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type DisciplineIncident struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	StudentID    uuid.NullUUID
	IncidentDate sql.NullTime
	Title        sql.NullString
	Description  sql.NullString
	Severity     sql.NullString
	ActionTaken  sql.NullString
	ReportedBy   uuid.NullUUID
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type DocsDocument struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	OwnerID     uuid.UUID
	OwnerType   sql.NullString
	DocType     sql.NullString
	FileName    sql.NullString
	FileUrl     string
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type EnumsAccountType struct {
	Code string
}

type EnumsAddressType struct {
	Code string
}

type EnumsAdmissionStatus struct {
	Code string
}

type EnumsAssignmentStatus struct {
	Code string
}

type EnumsAttendanceStatus struct {
	Code string
}

type EnumsBillingCycle struct {
	Code string
}

type EnumsBloodGroup struct {
	Code string
}

type EnumsChequeStatus struct {
	Code string
}

type EnumsCurrency struct {
	ID     int32
	Code   string
	Symbol sql.NullString
}

type EnumsDayOfWeek struct {
	Code      string
	SortOrder sql.NullInt32
}

type EnumsDocumentType struct {
	Code string
}

type EnumsExamType struct {
	Code string
}

type EnumsFeeFrequency struct {
	Code string
}

type EnumsFineType struct {
	Code string
}

type EnumsFuelType struct {
	Code string
}

type EnumsGender struct {
	Code string
}

type EnumsGradeSystemType struct {
	Code string
}

type EnumsHostelType struct {
	Code string
}

type EnumsIncidentSeverity struct {
	Code string
}

type EnumsInventoryTransactionType struct {
	Code string
}

type EnumsLeaveStatus struct {
	Code string
}

type EnumsLoanStatus struct {
	Code string
}

type EnumsMaintenanceType struct {
	Code string
}

type EnumsMaritalStatus struct {
	Code string
}

type EnumsMealType struct {
	Code string
}

type EnumsMemberType struct {
	Code string
}

type EnumsOwnerType struct {
	Code string
}

type EnumsPaymentMode struct {
	Code string
}

type EnumsPurchaseStatus struct {
	Code string
}

type EnumsRefundStatus struct {
	Code string
}

type EnumsRelationshipType struct {
	Code string
}

type EnumsSaasInvoiceStatus struct {
	Code string
}

type EnumsSocialCategory struct {
	Code string
}

type EnumsStockMovementType struct {
	Code string
}

type EnumsSubjectType struct {
	Code string
}

type EnumsSubscriptionStatus struct {
	Code string
}

type EnumsTaxType struct {
	Code string
}

type EnumsTicketPriority struct {
	Code string
}

type EnumsTicketStatus struct {
	Code string
}

type EnumsTripType struct {
	Code string
}

type EnumsUserRoleType struct {
	Code string
}

type EnumsVerificationStatus struct {
	Code string
}

type EnumsVisitorType struct {
	Code string
}

type ExamExam struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	Name              string
	StartDate         sql.NullTime
	EndDate           sql.NullTime
	IsPublished       sql.NullBool
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type ExamGradeRule struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	GradeSystemID uuid.UUID
	GradeName     sql.NullString
	MinPercentage sql.NullString
	MaxPercentage sql.NullString
	GradePoint    sql.NullString
	Description   sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type ExamGradeSystem struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	Type        sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type ExamMark struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	ScheduleID    uuid.UUID
	StudentID     uuid.UUID
	MarksObtained sql.NullString
	IsAbsent      sql.NullBool
	Remarks       sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
}

type ExamSchedule struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	ExamID          uuid.UUID
	ClassID         uuid.UUID
	SubjectID       uuid.UUID
	ExamDate        time.Time
	DurationMinutes sql.NullInt32
	MaxMarks        sql.NullString
	MinPassMarks    sql.NullString
	ExamType        sql.NullString
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type FinanceAccount struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	Name            string
	Code            string
	ParentAccountID uuid.NullUUID
	Type            string
	IsSystem        sql.NullBool
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type FinanceBankAccount struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	AccountName    sql.NullString
	AccountNumber  sql.NullString
	BankName       sql.NullString
	IfscCode       sql.NullString
	BranchName     sql.NullString
	OpeningBalance sql.NullString
	CurrentBalance sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type FinanceBankStatementEntry struct {
	ID                      uuid.UUID
	InstituteID             uuid.UUID
	BankAccountID           uuid.NullUUID
	TransactionDate         sql.NullTime
	ValueDate               sql.NullTime
	Description             sql.NullString
	WithdrawalAmount        sql.NullString
	DepositAmount           sql.NullString
	Balance                 sql.NullString
	ReconciledTransactionID uuid.NullUUID
	IsReconciled            sql.NullBool
	IsActive                sql.NullBool
	CreatedAt               sql.NullTime
	UpdatedAt               sql.NullTime
	DeletedAt               sql.NullTime
}

type FinanceBudget struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.NullUUID
	DepartmentID      uuid.NullUUID
	ExpenseCategoryID uuid.NullUUID
	AllocatedAmount   string
	UtilizedAmount    sql.NullString
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
}

type FinanceConcession struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	Type        sql.NullString
	Value       sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceFeeHead struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	Name              string
	IsRefundable      sql.NullBool
	LinkedGlAccountID uuid.NullUUID
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type FinanceFeeStructure struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	ClassID           uuid.NullUUID
	FeeHeadID         uuid.UUID
	Amount            string
	Frequency         sql.NullString
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type FinanceFineRule struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	GraceDays   sql.NullInt32
	FineType    sql.NullString
	FineAmount  sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceInvoice struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	InvoiceNo         string
	StudentID         uuid.UUID
	AcademicSessionID uuid.NullUUID
	TotalAmount       string
	DiscountAmount    sql.NullString
	FineAmount        sql.NullString
	PaidAmount        sql.NullString
	Status            sql.NullString
	DueDate           sql.NullTime
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type FinanceInvoiceItem struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	InvoiceID       uuid.UUID
	FeeHeadID       uuid.NullUUID
	Amount          string
	DiscountApplied sql.NullString
	ConcessionID    uuid.NullUUID
	Description     sql.NullString
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
}

type FinanceJournalEntry struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	ReferenceNo     sql.NullString
	TransactionDate sql.NullTime
	Description     sql.NullString
	IsPosted        sql.NullBool
	PostedAt        sql.NullTime
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type FinanceJournalItem struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	JournalEntryID uuid.UUID
	AccountID      uuid.UUID
	Debit          sql.NullString
	Credit         sql.NullString
	Description    sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
}

type FinancePurchaseItem struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	PurchaseOrderID uuid.UUID
	ItemID          uuid.UUID
	Quantity        int32
	UnitPrice       string
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
}

type FinancePurchaseOrder struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VendorID    uuid.UUID
	OrderDate   sql.NullTime
	TotalAmount sql.NullString
	Status      sql.NullString
	ReferenceNo sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinancePurchaseOrderItem struct {
	ID              uuid.UUID
	InstituteID     uuid.NullUUID
	PurchaseOrderID uuid.NullUUID
	ItemID          uuid.NullUUID
	Quantity        sql.NullInt32
	UnitPrice       sql.NullString
	TaxID           uuid.NullUUID
	TaxAmount       sql.NullString
	TotalAmount     sql.NullString
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type FinanceRefund struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	StudentID   uuid.NullUUID
	InvoiceID   uuid.NullUUID
	Amount      string
	Reason      sql.NullString
	Status      sql.NullString
	RefundDate  sql.NullTime
	ProcessedBy uuid.NullUUID
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type FinanceStudentWallet struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	StudentID   uuid.UUID
	Balance     sql.NullString
	IsActive    sql.NullBool
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type FinanceTax struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	Percentage  string
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type FinanceTransaction struct {
	ID               uuid.UUID
	InstituteID      uuid.UUID
	InvoiceID        uuid.NullUUID
	StudentID        uuid.NullUUID
	TransactionRefNo sql.NullString
	PaymentMode      sql.NullString
	ChequeNo         sql.NullString
	ChequeDate       sql.NullTime
	BankName         sql.NullString
	ChequeStatus     sql.NullString
	Amount           string
	IsWalletUsage    sql.NullBool
	PaymentDate      sql.NullTime
	Status           sql.NullString
	CollectedBy      uuid.NullUUID
	IsActive         sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	DeletedAt        sql.NullTime
	CreatedBy        uuid.NullUUID
	UpdatedBy        uuid.NullUUID
}

type FinanceVendor struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	ContactName sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	Address     sql.NullString
	GstNumber   sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetDriverProfile struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	EmployeeID         uuid.UUID
	LicenseNumber      sql.NullString
	LicenseExpiryDate  sql.NullTime
	VerificationStatus sql.NullString
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type FleetFuelLog struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	VehicleID       uuid.NullUUID
	FillDate        sql.NullTime
	QuantityLitres  sql.NullString
	Cost            sql.NullString
	OdometerReading sql.NullString
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type FleetMaintenanceLog struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	VehicleID       uuid.NullUUID
	MaintenanceType sql.NullString
	Description     sql.NullString
	Cost            sql.NullString
	ServiceDate     sql.NullTime
	NextServiceDue  sql.NullTime
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type FleetRoute struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	StartPoint  sql.NullString
	EndPoint    sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetRouteStop struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	RouteID       uuid.UUID
	StopName      sql.NullString
	PickupTime    sql.NullTime
	SequenceOrder sql.NullInt32
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
}

type FleetTripLog struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VehicleID   uuid.NullUUID
	DriverID    uuid.NullUUID
	RouteID     uuid.NullUUID
	TripType    sql.NullString
	TripDate    sql.NullTime
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetVehicle struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VehicleNo   string
	Model       sql.NullString
	Capacity    sql.NullInt32
	FuelType    sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FrontOfficePostalRecord struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	Type         sql.NullString
	SenderName   sql.NullString
	ReceiverName sql.NullString
	ReferenceNo  sql.NullString
	Date         sql.NullTime
	CreatedBy    uuid.NullUUID
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type FrontOfficeVisitor struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	VisitorType  sql.NullString
	Name         string
	Phone        sql.NullString
	Purpose      sql.NullString
	PersonToMeet uuid.NullUUID
	CheckIn      sql.NullTime
	CheckOut     sql.NullTime
	GatePassID   sql.NullString
	VehicleNo    sql.NullString
	CreatedBy    uuid.NullUUID
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type GeoCountry struct {
	ID                  uuid.UUID
	Name                string
	Code                sql.NullString
	DefaultCurrencyCode sql.NullString
	IsActive            sql.NullBool
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	CreatedBy           uuid.NullUUID
	UpdatedBy           uuid.NullUUID
}

type GeoDistrict struct {
	ID        uuid.UUID
	StateID   uuid.NullUUID
	Name      string
	Code      sql.NullString
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type GeoState struct {
	ID        uuid.UUID
	CountryID uuid.NullUUID
	Name      string
	Code      sql.NullString
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type HealthInfirmaryVisit struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	StudentID      uuid.UUID
	VisitDate      sql.NullTime
	Symptoms       sql.NullString
	TreatmentGiven sql.NullString
	AttendedBy     uuid.NullUUID
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type HealthMedicalRecord struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	StudentID       uuid.UUID
	BloodGroup      sql.NullString
	Allergies       sql.NullString
	Medications     sql.NullString
	EmergencyNotes  sql.NullString
	LastCheckupDate sql.NullTime
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type HealthVaccination struct {
	ID               uuid.UUID
	InstituteID      uuid.UUID
	StudentID        uuid.UUID
	VaccineName      sql.NullString
	DateAdministered sql.NullTime
	NextDueDate      sql.NullTime
	Remarks          sql.NullString
	IsActive         sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	DeletedAt        sql.NullTime
}

type HostelAllocation struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	RoomID            uuid.NullUUID
	StudentID         uuid.NullUUID
	AcademicSessionID uuid.NullUUID
	AllocationDate    sql.NullTime
	VacatedDate       sql.NullTime
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type HostelBuilding struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	Type        sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HostelRoom struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	BuildingID  uuid.NullUUID
	RoomNumber  sql.NullString
	Capacity    sql.NullInt32
	CostPerYear sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HrAttendanceDevice struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	DeviceName  sql.NullString
	IpAddress   sql.NullString
	Location    sql.NullString
	ApiKey      sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type HrBiometricLog struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	DeviceID    uuid.NullUUID
	UserID      uuid.NullUUID
	PunchTime   sql.NullTime
	PunchType   sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type HrLeaveApplication struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	EmployeeID  uuid.NullUUID
	LeaveTypeID uuid.NullUUID
	StartDate   time.Time
	EndDate     sql.NullTime
	Reason      sql.NullString
	Status      sql.NullString
	ApprovedBy  uuid.NullUUID
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HrLeaveType struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	Name               sql.NullString
	DaysAllowedPerYear sql.NullInt32
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type InventoryFixedAsset struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	ItemID       uuid.NullUUID
	AssetTagID   sql.NullString
	SerialNumber sql.NullString
	LocationRoom sql.NullString
	PurchaseDate sql.NullTime
	PurchaseCost sql.NullString
	Status       sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type InventoryItem struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	Name         sql.NullString
	CategoryID   uuid.NullUUID
	IsFixedAsset sql.NullBool
	ReorderLevel sql.NullInt32
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type InventoryItemCategory struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type InventoryLocation struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	InChargeID  uuid.NullUUID
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type InventoryRequisition struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	RequestedBy  uuid.UUID
	DepartmentID uuid.NullUUID
	Status       sql.NullString
	RequestDate  sql.NullTime
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type InventoryRequisitionItem struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	RequisitionID uuid.UUID
	ItemName      sql.NullString
	Quantity      sql.NullInt32
	Remarks       sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type InventoryStockLevel struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	ItemID      uuid.NullUUID
	LocationID  uuid.NullUUID
	Quantity    sql.NullInt32
	IsActive    sql.NullBool
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type InventoryStockTransfer struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	ItemID         uuid.NullUUID
	FromLocationID uuid.NullUUID
	ToLocationID   uuid.NullUUID
	Quantity       sql.NullInt32
	MovedBy        uuid.NullUUID
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type InventoryTransaction struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	ItemID          uuid.NullUUID
	TransactionType sql.NullString
	Quantity        sql.NullInt32
	UnitPrice       sql.NullString
	Remarks         sql.NullString
	TransactionDate sql.NullTime
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type LibraryBook struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	Title           string
	Author          sql.NullString
	Isbn            sql.NullString
	CategoryID      uuid.NullUUID
	TotalCopies     sql.NullInt32
	AvailableCopies sql.NullInt32
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type LibraryBookIssue struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	BookID      uuid.NullUUID
	MemberID    uuid.UUID
	MemberType  sql.NullString
	IssueDate   sql.NullTime
	DueDate     time.Time
	ReturnDate  sql.NullTime
	FineAmount  sql.NullString
	Status      sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type LibraryCategory struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type LibraryCirculationRule struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	MemberType     sql.NullString
	MaxBooksIssued sql.NullInt32
	IssueDaysLimit sql.NullInt32
	FinePerDay     sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type PayrollEmployeeSalaryConfig struct {
	ID          uuid.UUID
	EmployeeID  uuid.UUID
	ComponentID uuid.UUID
	Amount      string
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type PayrollLoan struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	EmployeeID        uuid.NullUUID
	Amount            string
	InterestRate      sql.NullString
	InstallmentAmount sql.NullString
	TotalInstallments sql.NullInt32
	PaidInstallments  sql.NullInt32
	Status            sql.NullString
	ApprovedBy        uuid.NullUUID
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
}

type PayrollPayslip struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	EmployeeID      uuid.UUID
	MonthYear       time.Time
	GrossSalary     sql.NullString
	TotalDeductions sql.NullString
	NetSalary       sql.NullString
	IsPaid          sql.NullBool
	PaymentDate     sql.NullTime
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type PayrollSalaryComponent struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	IsDeduction sql.NullBool
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type SubscriptionInvoice struct {
	ID                 uuid.UUID
	SubscriptionID     uuid.NullUUID
	Amount             string
	Status             sql.NullString
	BillingPeriodStart sql.NullTime
	BillingPeriodEnd   sql.NullTime
	IssuedAt           sql.NullTime
	PaidAt             sql.NullTime
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
}

type SubscriptionPayment struct {
	ID             uuid.UUID
	InvoiceID      uuid.NullUUID
	TransactionRef sql.NullString
	Amount         sql.NullString
	PaymentDate    sql.NullTime
	Status         sql.NullString
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type SubscriptionPlan struct {
	ID              uuid.UUID
	Name            string
	BasePrice       string
	PricePerStudent string
	CurrencyCode    sql.NullString
	BillingCycle    sql.NullString
	Features        pqtype.NullRawMessage
	IsActive        sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type SubscriptionSubscription struct {
	ID                   uuid.UUID
	InstituteID          uuid.UUID
	PlanID               uuid.UUID
	Status               sql.NullString
	StartDate            time.Time
	EndDate              time.Time
	NextBillingDate      sql.NullTime
	StudentCountSnapshot sql.NullInt32
	IsActive             sql.NullBool
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	DeletedAt            sql.NullTime
	CreatedBy            uuid.NullUUID
	UpdatedBy            uuid.NullUUID
}

type SupportTicket struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	RaisedBy    uuid.NullUUID
	CategoryID  uuid.NullUUID
	Priority    sql.NullString
	Status      sql.NullString
	Subject     sql.NullString
	Description sql.NullString
	AssignedTo  uuid.NullUUID
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type SupportTicketCategory struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type SupportTicketComment struct {
	ID        uuid.UUID
	TicketID  uuid.NullUUID
	UserID    uuid.NullUUID
	Comment   sql.NullString
	IsActive  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
