// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AcademicsClassPeriod struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	StartTime   time.Time
	EndTime     time.Time
	IsBreak     sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type AcademicsSubject struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	Code        sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type AcademicsTimetableEntry struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	ClassID           uuid.NullUUID
	PeriodID          uuid.NullUUID
	SubjectID         uuid.NullUUID
	TeacherID         uuid.NullUUID
	DayOfWeek         sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type AdmissionsEnquiry struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	StudentName  sql.NullString
	GuardianName sql.NullString
	Phone        sql.NullString
	Email        sql.NullString
	Status       sql.NullString
	EnquiryDate  sql.NullTime
	FollowUpDate sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type AuthUser struct {
	ID             uuid.UUID
	Username       string
	PasswordHash   string
	RoleType       sql.NullString
	LinkedEntityID uuid.UUID
	InstituteID    uuid.NullUUID
	IsActive       sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
	UpdatedBy      uuid.NullUUID
}

type CommsNotification struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	UserID      uuid.NullUUID
	Title       sql.NullString
	Message     sql.NullString
	IsRead      sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CoreAcademicSession struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	StartDate   time.Time
	EndDate     time.Time
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CoreAddress struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	OwnerType    sql.NullString
	AddressType  sql.NullString
	AddressLine1 string
	AddressLine2 sql.NullString
	CountryID    uuid.NullUUID
	StateID      uuid.NullUUID
	DistrictID   uuid.NullUUID
	PostalCode   sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type CoreClass struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	Name              string
	Section           string
	ClassTeacherID    uuid.NullUUID
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type CoreDepartment struct {
	ID          uuid.UUID
	InstituteID uuid.NullUUID
	Name        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type CoreEmployee struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	EmployeeCode       string
	FirstName          string
	LastName           sql.NullString
	DepartmentID       uuid.NullUUID
	Gender             sql.NullString
	MaritalStatus      sql.NullString
	DateOfJoining      sql.NullTime
	Nationality        sql.NullString
	PreferredLanguage  sql.NullString
	SocialMediaHandles pqtype.NullRawMessage
	LanguageSkills     pqtype.NullRawMessage
	IsActive           sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type CoreGuardian struct {
	ID           uuid.UUID
	FirstName    string
	LastName     sql.NullString
	Email        sql.NullString
	Phone        sql.NullString
	Profession   sql.NullString
	AnnualIncome sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type CoreInstitute struct {
	ID           uuid.UUID
	Name         string
	Code         string
	CurrencyCode sql.NullString
	LogoUrl      sql.NullString
	Website      sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type CoreStudent struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	AdmissionNo        string
	FirstName          string
	LastName           sql.NullString
	Dob                sql.NullTime
	Gender             sql.NullString
	BloodGroup         sql.NullString
	SocialCategory     sql.NullString
	CurrentClassID     uuid.NullUUID
	Nationality        sql.NullString
	PreferredLanguage  sql.NullString
	SocialMediaHandles pqtype.NullRawMessage
	LanguageSkills     pqtype.NullRawMessage
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type CoreStudentGuardianMap struct {
	StudentID        uuid.UUID
	GuardianID       uuid.UUID
	Relationship     sql.NullString
	IsPrimaryContact sql.NullBool
	CreatedAt        sql.NullTime
}

type DocsDocument struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	OwnerID     uuid.UUID
	OwnerType   sql.NullString
	DocType     sql.NullString
	FileName    sql.NullString
	FileUrl     string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type EnumsAccountType struct {
	Code string
}

type EnumsAddressType struct {
	Code string
}

type EnumsAdmissionStatus struct {
	Code string
}

type EnumsAttendanceStatus struct {
	Code string
}

type EnumsBloodGroup struct {
	Code string
}

type EnumsCurrency struct {
	ID     int32
	Code   string
	Symbol sql.NullString
}

type EnumsDayOfWeek struct {
	Code      string
	SortOrder sql.NullInt32
}

type EnumsDocumentType struct {
	Code string
}

type EnumsFeeFrequency struct {
	Code string
}

type EnumsFineType struct {
	Code string
}

type EnumsGender struct {
	Code string
}

type EnumsHostelType struct {
	Code string
}

type EnumsInventoryTransactionType struct {
	Code string
}

type EnumsLeaveStatus struct {
	Code string
}

type EnumsMaritalStatus struct {
	Code string
}

type EnumsMemberType struct {
	Code string
}

type EnumsOwnerType struct {
	Code string
}

type EnumsPaymentMethod struct {
	Code string
}

type EnumsPurchaseStatus struct {
	Code string
}

type EnumsRelationshipType struct {
	Code string
}

type EnumsSocialCategory struct {
	Code string
}

type EnumsTripType struct {
	Code string
}

type EnumsUserRoleType struct {
	Code string
}

type EnumsVerificationStatus struct {
	Code string
}

type FinanceAccount struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	Code        string
	Type        string
	Description sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceFeeHead struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceFeeStructure struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	AcademicSessionID uuid.UUID
	ClassID           uuid.NullUUID
	FeeHeadID         uuid.UUID
	Amount            string
	Frequency         sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type FinanceFineRule struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	GraceDays   sql.NullInt32
	FineType    sql.NullString
	FineAmount  sql.NullString
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceInvoice struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	InvoiceNo   string
	StudentID   uuid.UUID
	TotalAmount string
	PaidAmount  sql.NullString
	Status      sql.NullString
	DueDate     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceInvoiceItem struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	InvoiceID   uuid.UUID
	FeeHeadID   uuid.NullUUID
	Description sql.NullString
	Amount      string
	CreatedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
}

type FinanceJournalEntry struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	ReferenceNo     sql.NullString
	TransactionDate sql.NullTime
	Description     sql.NullString
	IsPosted        sql.NullBool
	PostedAt        sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type FinanceJournalItem struct {
	ID             uuid.UUID
	InstituteID    uuid.UUID
	JournalEntryID uuid.UUID
	AccountID      uuid.UUID
	Debit          sql.NullString
	Credit         sql.NullString
	Description    sql.NullString
	CreatedAt      sql.NullTime
	CreatedBy      uuid.NullUUID
}

type FinancePurchaseItem struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	PurchaseOrderID uuid.UUID
	ItemID          uuid.UUID
	Quantity        int32
	UnitPrice       string
	CreatedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
}

type FinancePurchaseOrder struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VendorID    uuid.UUID
	OrderDate   sql.NullTime
	TotalAmount sql.NullString
	Status      sql.NullString
	ReferenceNo sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FinanceTransaction struct {
	ID               uuid.UUID
	InstituteID      uuid.UUID
	InvoiceID        uuid.NullUUID
	TransactionRefNo sql.NullString
	PaymentMethod    sql.NullString
	Amount           string
	PaymentDate      sql.NullTime
	Status           sql.NullString
	CollectedBy      uuid.NullUUID
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	CreatedBy        uuid.NullUUID
	UpdatedBy        uuid.NullUUID
}

type FinanceVendor struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	ContactName sql.NullString
	Phone       sql.NullString
	Email       sql.NullString
	Address     sql.NullString
	GstNumber   sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetDriverProfile struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	EmployeeID         uuid.UUID
	LicenseNumber      sql.NullString
	LicenseExpiryDate  sql.NullTime
	VerificationStatus sql.NullString
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type FleetRoute struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	StartPoint  sql.NullString
	EndPoint    sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetRouteStop struct {
	ID            uuid.UUID
	InstituteID   uuid.UUID
	RouteID       uuid.UUID
	StopName      sql.NullString
	PickupTime    sql.NullTime
	SequenceOrder sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	CreatedBy     uuid.NullUUID
	UpdatedBy     uuid.NullUUID
}

type FleetTripLog struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VehicleID   uuid.NullUUID
	DriverID    uuid.NullUUID
	RouteID     uuid.NullUUID
	TripType    sql.NullString
	TripDate    sql.NullTime
	StartTime   sql.NullTime
	EndTime     sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type FleetVehicle struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	VehicleNo   string
	Model       sql.NullString
	Capacity    sql.NullInt32
	IsActive    sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type GeoCountry struct {
	ID                  uuid.UUID
	Name                string
	Code                sql.NullString
	DefaultCurrencyCode sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	CreatedBy           uuid.NullUUID
	UpdatedBy           uuid.NullUUID
}

type GeoDistrict struct {
	ID        uuid.UUID
	StateID   uuid.NullUUID
	Name      string
	Code      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type GeoState struct {
	ID        uuid.UUID
	CountryID uuid.NullUUID
	Name      string
	Code      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	CreatedBy uuid.NullUUID
	UpdatedBy uuid.NullUUID
}

type HostelAllocation struct {
	ID                uuid.UUID
	InstituteID       uuid.UUID
	RoomID            uuid.NullUUID
	StudentID         uuid.NullUUID
	AcademicSessionID uuid.NullUUID
	AllocationDate    sql.NullTime
	VacatedDate       sql.NullTime
	IsActive          sql.NullBool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	CreatedBy         uuid.NullUUID
	UpdatedBy         uuid.NullUUID
}

type HostelBuilding struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	Type        sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HostelRoom struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	BuildingID  uuid.NullUUID
	RoomNumber  sql.NullString
	Capacity    sql.NullInt32
	CostPerYear sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HrLeaveApplication struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	EmployeeID  uuid.NullUUID
	LeaveTypeID uuid.NullUUID
	StartDate   time.Time
	EndDate     sql.NullTime
	Reason      sql.NullString
	Status      sql.NullString
	ApprovedBy  uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type HrLeaveType struct {
	ID                 uuid.UUID
	InstituteID        uuid.UUID
	Name               sql.NullString
	DaysAllowedPerYear sql.NullInt32
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	CreatedBy          uuid.NullUUID
	UpdatedBy          uuid.NullUUID
}

type InventoryItem struct {
	ID           uuid.UUID
	InstituteID  uuid.UUID
	Name         sql.NullString
	CategoryID   uuid.NullUUID
	CurrentStock sql.NullInt32
	ReorderLevel sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CreatedBy    uuid.NullUUID
	UpdatedBy    uuid.NullUUID
}

type InventoryItemCategory struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type InventoryTransaction struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	ItemID          uuid.NullUUID
	TransactionType sql.NullString
	Quantity        sql.NullInt32
	UnitPrice       sql.NullString
	Remarks         sql.NullString
	TransactionDate sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type LibraryBook struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	Title           string
	Author          sql.NullString
	Isbn            sql.NullString
	CategoryID      uuid.NullUUID
	TotalCopies     sql.NullInt32
	AvailableCopies sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type LibraryBookIssue struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	BookID      uuid.NullUUID
	MemberID    uuid.UUID
	MemberType  sql.NullString
	IssueDate   sql.NullTime
	DueDate     time.Time
	ReturnDate  sql.NullTime
	FineAmount  sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type LibraryCategory struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type PayrollEmployeeSalaryConfig struct {
	ID          uuid.UUID
	EmployeeID  uuid.UUID
	ComponentID uuid.UUID
	Amount      string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}

type PayrollPayslip struct {
	ID              uuid.UUID
	InstituteID     uuid.UUID
	EmployeeID      uuid.UUID
	MonthYear       time.Time
	GrossSalary     sql.NullString
	TotalDeductions sql.NullString
	NetSalary       sql.NullString
	IsPaid          sql.NullBool
	PaymentDate     sql.NullTime
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	CreatedBy       uuid.NullUUID
	UpdatedBy       uuid.NullUUID
}

type PayrollSalaryComponent struct {
	ID          uuid.UUID
	InstituteID uuid.UUID
	Name        string
	IsDeduction sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	CreatedBy   uuid.NullUUID
	UpdatedBy   uuid.NullUUID
}
