name: Validate Pull Request

on: pull_request

env:
  GO_VERSION_FILE: 'go.mod'

jobs:
  run-lint:
    name: Run Linter
    runs-on: [main]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  run-tests:
    name: Run Tests
    needs: [run-lint]
    runs-on: [main]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.GO_VERSION_FILE }}
          cache: false
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
      - name: Run Tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee //tmp/gotest.log | gotestfmt