package core

import (
	"context"
	"errors"

	"swiftschool/domain"
	"swiftschool/mapper"

	"github.com/google/uuid"
)

// CreateClass inserts a new class record into the database
func (r *Repository) CreateClass(ctx context.Context, arg domain.Class) (*domain.Class, error) {
	ctx, cancel := r.db.WithTimeout(ctx)
	defer cancel()

	q, err := r.db.Queries()
	if err != nil {
		return nil, err
	}

	params := mapper.MapDomainClassToDBParams(arg)
	row, err := q.CreateClass(ctx, params)
	if err != nil {
		return nil, err
	}

	out := mapper.MapDBClassToDomain(row)
	return &out, nil
}

// DeleteClass removes a class record from the database
func (r *Repository) DeleteClass(ctx context.Context, id uuid.UUID) error {
	// DeleteClass query not generated by SQLC
	return errors.New("delete class not implemented")
}

// ListClasses retrieves all classes for an institute from the database
func (r *Repository) ListClasses(ctx context.Context, instituteID uuid.UUID) ([]*domain.Class, error) {
	ctx, cancel := r.db.WithTimeout(ctx)
	defer cancel()

	// q, err := r.db.Queries()
	// if err != nil {
	// 	return nil, err
	// }

	// ListClasses requires AcademicSessionID, but GetActiveSession query is missing.
	return nil, errors.New("list classes not implemented (missing active session query)")
	/*
		rows, err := q.ListClasses(ctx, db.ListClassesParams{
			InstituteID:       instituteID,
			AcademicSessionID: uuid.Nil, // Needed?
		})
		if err != nil {
			return nil, err
		}
		var classes []*domain.Class
		for _, row := range rows {
			c := mapper.MapDBListClassesRowToDomain(row)
			classes = append(classes, &c)
		}
		return classes, nil
	*/
}

// UpdateClass updates an existing class record in the database
func (r *Repository) UpdateClass(ctx context.Context, arg domain.Class) (*domain.Class, error) {
	// UpdateClass query not generated by SQLC
	return nil, errors.New("update class not implemented")
}
