package core

import (
	"context"
	"errors"
	"swiftschool/domain"
	"swiftschool/mapper"

	"github.com/google/uuid"
)

// CreateAcademicSession creates a new academic session
func (r *Repository) CreateAcademicSession(ctx context.Context, arg domain.AcademicSession) (*domain.AcademicSession, error) {
	ctx, cancel := r.db.WithTimeout(ctx)
	defer cancel()

	q, err := r.db.Queries()
	if err != nil {
		return nil, err
	}

	params := mapper.MapDomainAcademicSessionToDBParams(arg)
	row, err := q.CreateAcademicSession(ctx, params)
	if err != nil {
		return nil, err
	}

	out := mapper.MapDBAcademicSessionToDomain(row)
	return &out, nil
}

// GetActiveSession retrieves the active academic session for an institute
func (r *Repository) GetActiveSession(ctx context.Context, instituteID uuid.UUID) (*domain.AcademicSession, error) {
	// Active Academic Session query not generated by SQLC
	return nil, errors.New("get active academic session not implemented")
}

// ListAcademicSessions retrieves all academic sessions for an institute
func (r *Repository) ListAcademicSessions(ctx context.Context, instituteID uuid.UUID) ([]*domain.AcademicSession, error) {
	// Query not generated or problematic?
	// Stubbing for now to pass build as per previous attempts
	return nil, errors.New("list academic sessions not implemented")
}

// UpdateAcademicSession updates an existing academic session
func (r *Repository) UpdateAcademicSession(ctx context.Context, arg domain.AcademicSession) (*domain.AcademicSession, error) {
	// Stubbed
	return nil, errors.New("update academic session not implemented")
}
